///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommingSoonMovieListModelDataMovielist {
/*
{
  "id": 235,
  "name": "KADAW",
  "description": "This is discrption&nbsp;",
  "longDescription": "<p>This is discrption&nbsp;</p>",
  "type": "Movies",
  "poster": "http://prabhu.yoursoftwaredemo.com/uploads/movie/1761968070758551.jpg",
  "isReminder": 0
}
*/

  int? id;
  String? name;
  String? description;
  String? longDescription;
  String? type;
  String? poster;
  int? isReminder;

  CommingSoonMovieListModelDataMovielist({
    this.id,
    this.name,
    this.description,
    this.longDescription,
    this.type,
    this.poster,
    this.isReminder,
  });
  CommingSoonMovieListModelDataMovielist.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    longDescription = json['longDescription']?.toString();
    type = json['type']?.toString();
    poster = json['poster']?.toString();
    isReminder = json['isReminder']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['longDescription'] = longDescription;
    data['type'] = type;
    data['poster'] = poster;
    data['isReminder'] = isReminder;
    return data;
  }
}

class CommingSoonMovieListModelData {
/*
{
  "movielist": [
    {
      "id": 235,
      "name": "KADAW",
      "description": "This is discrption&nbsp;",
      "longDescription": "<p>This is discrption&nbsp;</p>",
      "type": "Movies",
      "poster": "http://prabhu.yoursoftwaredemo.com/uploads/movie/1761968070758551.jpg",
      "isReminder": 0
    }
  ]
}
*/

  List<CommingSoonMovieListModelDataMovielist?>? movielist;

  CommingSoonMovieListModelData({
    this.movielist,
  });
  CommingSoonMovieListModelData.fromJson(Map<String, dynamic> json) {
    if (json['movielist'] != null) {
      final v = json['movielist'];
      final arr0 = <CommingSoonMovieListModelDataMovielist>[];
      v.forEach((v) {
        arr0.add(CommingSoonMovieListModelDataMovielist.fromJson(v));
      });
      movielist = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (movielist != null) {
      final v = movielist;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['movielist'] = arr0;
    }
    return data;
  }
}

class CommingSoonMovieListModel {
  bool? status;
  String? message;
  CommingSoonMovieListModelData? data;

  CommingSoonMovieListModel({
    this.status,
    this.message,
    this.data,
  });
  CommingSoonMovieListModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? CommingSoonMovieListModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
