import 'package:get/get.dart';

class WorldLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_Hindi': {
          'HelloMegha': 'हेलो मेघालय',
          "Not Registered yet?": " पंजीकरण नहीं किया?",
          "Register": "पंजीकरण करवाना",
          "Reset Password": " पासवर्ड रीसेट करें",
          "Change Password": " पासवर्ड बदलें",
          "Create Account": ' नया अकाउंट बनाएँ  or खाता बनाएं',
          "Old password": " पुराना पासवर्ड",
          "Password": " पासवर्ड",
          "First Name": " प्रथम नाम",
          "Last Name": "उपनाम",
          "Email": " ईमेल",
          "User Name": "उपयोगकर्ता नाम",
          "Create Password": "पासवर्ड बनाएं",
          "New Password": "नया पासवर्ड",
          "Enter email or mobile number": "ईमेल या मोबाइल नंबर दर्ज करें",
          "Logout": " लॉग आउट",
          "EPIC": "ईपीआईसी",
          "Back to ": "वापस",
          "Back": 'वापस ',
          "Home": " होम ",
          "Account": " खाता ",
          "Support": " सहायता ",
          "Email us": "हमें ईमेल करें",
          "Email": " ईमेल ",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Contact us": " हमसे संपर्क करें",
          "No Internet connection.": " इंटरनेट कनेक्शन नहीं है",
          "+91-": "+91-",
          "Edit Account details": " खाता विवरण संपादित करें",
          "Update Profile/Account": " प्रोफ़ाइल/खाता अपडेट करें ",
          "Enter your first name here": " अपना प्रथम नाम यहाँ दर्ज करें ",
          "Enter your last name here": " अपना उपनाम यहाँ दर्ज करें ",
          "Enter Password": " पासवर्ड डालें ",
          "Enter mobile number": " मोबाइल नंबर डालें ",
          "Verify OTP": "ओटीपी की पुष्टि करें",
          "Create new password": "नया पासवर्ड बनाएं",
          "Forgot password? Reset here": "पासवर्ड भूल गए? यहां रीसेट करें",
          "Tell me about yourself by signing up":
              "साइन अप करके अपने बारे में मुझे बताएं",
          "Login": "लॉग इन करें",
          "Forgot Password": "पासवर्ड भूल गए",
          "Send OTP": "ओटीपी भेजें",
          "Email OTP": " ईमेल ओटीपी ",
          "Resend OTP": " ओटीपी पुनः भेजें ",
          "Continue": " जारी रखें ",
          "Next": " अगला ",
          "Finish": " समाप्त ",
          "Full Name": " पूरा नाम ",
          "Mobile": " मोबाइल ",
          "Mobile Number": " मोबाइल नंबर ",
          "Choose Avatar": " अवतार चुनें ",
          "Please enter valid OTP": " कृपया मान्य ओटीपी डालें ",
          "CREATE ACCOUNT": 'नया अकाउंट बनाएँ  or खाता बनाएं ',
          "Disclaimer": " अस्वीकरण ",
          "Forgot Password?": " पासवर्ड भूल गए?",
          "Yes": " हाँ ",
          "No": " नहीं ",
          "Are you sure, do you want to logout?":
              " क्या आप सुनिश्चित हैं, क्या आप लॉगआउट करना चाहते हैं?",
          "Select": " चयन करें ",
          "Existing user?": "मौजूदा उपयोगकर्ता?",
          "LOG IN": " लॉग इन करें ",
          "Please enter first name": " कृपया प्रथम नाम दर्ज करें ",
          "Please enter last name": " कृपया उपनाम दर्ज करें ",
          "Email required": " ईमेल (अनिवार्य)",
          "Password required": " पासवर्ड (अनिवार्य)",
          "Please enter a valid email address":
              " कृपया एक मान्य ईमेल पता दर्ज करें",
          "Password not matched": " पासवर्ड मेल नहीं खाता",
          "Enter valid password": "मान्य पासवर्ड दर्ज करें",
          "Please enter full name": "कृपया पूरा नाम दर्ज करें",
          "Please enter valid number": " कृपया वैध नंबर डालें",
          "OK": "ठीक है",
          "Edit and Update": "एडिट और अपडेट करें",
          "KYC Update": "केवाईसी अपडेट",
          "Update": "अपडेट करें",
          "Are you sure?": "क्या आप निश्चित हैं?",
          "Live will stop": "लाइव रुक जाएगा",
          "Cancel": "रद्द करें",
          "Exit": "बाहर निकलें",
          'Notifications': 'सूचनाएं',
          'No Internet connection found. Check your connection or try again':
              'कोई इंटरनेट कनेक्शन नहीं मिला। अपना कनेक्शन जांचें या फिर से कोशिश करें',
          'Please Verify\nYour': 'कृपया पुष्टि करेंअपना',
          'Enter the 4-digit code sent to':
              '4 अंकों का कोड दर्ज करें जिसे भेजा गया',
          'App Settings': 'ऐप सेटिंग्स',
          'Video Playback ': 'वीडियो प्लेबैक',
          'Downloads': 'डाउनलोड',
          'Wi-Fi Only': 'केवल वाई-फाई',
          'Let\'s Get ': 'प्राप्त करें',
          'Started': 'शुरू',
          'Let\'s Get Started': 'आइए शुरू करें',
          'My List': 'मेरी सूची',
          'Password must contain 1 special 1 capital and 1 small character':
              'पासवर्ड में 1 विशेष, 1 बड़ा अक्षर और 1 छोटा वर्ण होना चाहिए ',
          'Please check your network': 'कृपया अपना नेटवर्क जांचें',
          'Stories': 'कहानियां',
          'Continue Watching': 'देखना जारी रखें',
          'Today\'s Top 10 Picks': 'आज के शीर्ष 10 चयन',
          'Winner of': 'के विजेता',
          'What is happening in universe': 'ब्रह्मांड में क्या हो रहा है',
          'Amrit Kumar': 'अमृत कुमार ',
          'Quiz': 'प्रश्नोत्तरी',
          'Monthly Quiz': 'मासिक प्रश्नोत्तरी',
          'Weekly Quiz': 'साप्ताहिक प्रश्नोत्तरी',
          'Hot Videos': 'हॉट वीडियो',
          'Scheme Videos': 'योजना वीडियो',
          'Recommend Videos': 'अनुशंसित वीडियो',
          'Live Stream': 'लाइव स्ट्रीम',
          'Click on watch live': 'लाइव देखने के लिए क्लिक करें',
          'Watch Live': 'लाइव देखें',
          'Live stream will start soon...': 'लाइव स्ट्रीम जल्द ही शुरू होगा...',
          'Get Start': 'आरंभ करें',
          'Short Films': 'लघु फिल्म',
          'Go': 'जाना',
          'Strings.stories': 'स्ट्रिंग्स.स्टोरीज़',
          'Influncers videos': 'इन्फ्लुएंसर वीडियो',
          'Continue Watching': 'देखना जारी रखें',
          'Today\'s Top 10 Picks': 'आज के शीर्ष 10 चयन',
          'Comedy': 'कॉमेडी',
          'Horror': 'हॉरर',
          'Romantic': 'रोमांटिक',
          'Music videos': 'म्यूजिक वीडियोज',
          'Music Artists': 'संगीत कलाकार',
          'Music Album ': 'संगीत एल्बम',
          'Trending Music': 'ट्रेंडिंग म्यूजिक',
          'Hot Music': 'हॉट म्यूजिक',
          'Music': 'संगीत',
          '80 Music': '80 के दशक का संगीत',
          'Coming Soon': 'जल्द आ रहा है',
          'No Downloaded Available': 'कोई डाउनलोड उपलब्ध नहीं',
          'Are you sure? you want to to delete':
              'क्या आप सुनिश्चित हैं? आप डिलीट करना चाहते हैं?',
          'Delete': 'डिलीट',
          'No Downloaded Movies available':
              'कोई डाउनलोड की गई फिल्में उपलब्ध नहीं हैं',
          ' All  ': '  सब ',
          'Movies': 'फिल्में',
          'Music Video': ' म्यूजिक वीडियो',
          'Videos': 'वीडिो',
          'KYC ': 'केवाईसी',
          'Let\'s Get ': 'प्राप्त करें',
          'Bank Statement': 'बैंक स्टेटमेंट',
          'More': 'और',
          'Available': 'उपलब्ध',
          'Delete account': 'डिलीट एकाउंट',
          'Are you sure, you want to delete the Account?':
              'क्या आप सुनिश्चित हैं, आप खाता डिलीट करना चाहते हैं?',
          'Premium | U/A 7+': 'प्रीमियम | यू/ए 7+',
          '2019 . Sci-fi . Action': '2019। साइंस फिक्शन।',
          'Watch List': 'देखें सूची',
          'Cast': 'कास्ट',
          'Directer & Writers': 'निर्देशक और लेखक',
          'Similar movies': 'मिलती-जुलती फिल्में',
          'Premium | U/A 11+': 'प्रीमियम | यू/ए 11+',
          'No movie available': 'कोई फिल्म उपलब्ध नहीं',
          'Similar content': 'समान कंटेंट',
          'Filter': 'फ़िल्टर',
          'Streaming': 'स्ट्रीमिंग',
          'Click on watch live': 'लाइव देखने के लिए क्लिक करें',
          'Withdraw ': 'वापस लेना',
          'All Transactions': 'सभी लेन - देन',
          'Order ID': 'ऑर्डर आईडी',
          'Name': 'नाम',
          'Transaction Id': 'ट्रांजैक्शन आईडी',
          'Processing': 'प्रोसेसिंग',
          'Are you sure?': 'क्या आप सुनिश्चित हैं?',
          'Coins will convert into amount': 'सिक्के रकम में बदल जाएंगे',
          'Can\'t withdraw': 'वापसी नहीं कर सकता',
          'Don\'t have amount': 'राशि नहीं है'
        },
        'en_garo': {
          'Similar movies': 'Apsananggipa filmrang',
          'Music': 'Doka-dam•ani ba ring•aniranv',
          'Password must contain 1 special 1 capital and 1 small character':
              'Passwordo ge•sa special ge•sa capital aro ge•sa chongipa oikorrang dongna nanggen',
          'Password required min length 7':
              'Password komibeoba ming 7 oikorrang dongna nanggen',
          'Request cancelled': 'Requestko jegalaha',
          'Server unreachable': 'Server-ona sokna man•jaenga',
          'Something went wrong': 'Maiaba ong•jaha',
          'Please try again': 'Jotton ka•e nitaibo',
          'All as playlist': 'Pilakkon playlist dake',
          'Now Playing': 'Da•o watenggipa',
          'Play All': 'Pilakkon watbo',
          'Your score': 'Nang•ni score',
          "Looks like you have answered one or more questions incorrectly. Try your luck with other games.":
              "Sing•anirangko na•a mingsa ba una bate ong•gija aganchakaha. Gipin kal•anirangko kal•skae nibo.",
          'Play & Collect Coins': 'Kal•bo aro bisilrangko chimongbo',
          'Terms & Conditions': 'Pangchakanirang aro niamrang',
          "Let's Play Quiz": "Hai Quiz kal•na",
          "Lets Start Quiz": "Hai Quiz a•bachengna",
          'Winners': 'Chegiparang',
          'Weekly Winners': 'Antiprako chegiparang',
          'Filter': 'Filter',
          'Winner name': 'Chegipani bimung',
          'Monthly Winners': 'Japrako chegiparang',
          'Mobile number is required': 'Mobile numberko nanggen',
          'Mobile number must be 10 digits':
              'Mobile number ge 10 numberrang ong•na nanggen',
          'Enter 10 digits mobile':
              'Mobile numberni ge-10 numberrangko gapatbo',
          'Recommend Music Videos': 'Music Videorangko janapatbo',
          "Music Video": "Music Video",
          'Notifications': 'U•iatanirang',
          'Language': 'Ku•sik',
          'Enter the 5 digit code sent to':
              'Watatgimin ge-5 numberrangko gapatbo',
          'Please enter phone number': 'Phone numberko gapatbo',
          'Date Of Birth is required': 'Atchiani tarikko gapatna nanggrn',
          "Select Your City": "Nangni donggipa biapko basebo",
          'City is required': 'Nangni donggipa biapko gapatna nanggen',
          "View KYC": "KYCko nibo",
          'Upload': 'Gatatbo',
          '* required': '* nanggen',
          'Account Number': 'Account Number',
          'Enter Account Number': 'Account Numberko gapatbo',
          'Enter IFSC Code': 'IFSC Codeko gapatbo',
          'AADHAR Number': 'AADHAR Number',
          'IFSC Code': 'IFSC Code',
          'Voter ID': 'Voter ID',
          'Enter Voter ID': ' Voter IDko gapatbo',
          'Bank Name': 'Bankni bimung',
          'Enter Bank name': ' Bankni bimungko gapatbo',
          'Update Kyc': 'Kycko update ka•bo',
          "Please Fill up all the details": "Pilak janapgiminrangkon gapatbo",
          'App Settings': 'App Settings',
          'Video Playback': 'Video Playback',
          'Cellular Data Usage': 'Cellular Data jakkalani',
          'Allow Notifications': 'U•iatanirangko sokatna on•bo',
          'Customize in Settings': 'Settings-o an•tangni nangnika gita taribo',
          'Download Video Quality': 'Video Qualityko download ka•bo',
          'Select Download Video Quality': 'Download Video Qualityko basebo',
          'Play Video Quality': ' Play Video Quality',
          "Select Play Video Quality": "Play Video Qualityko basebo",
          'Download Location': 'Locationko download ka•bo',
          "Select Download Location": "Download Locationko basebo",
          'Delete All Downloads': 'Pilak downloadrangko kimite galbo',
          'Are you sure? you want to to delete all download?':
              'Na•a pilak download ka•giminrangko kimite ba ra•gale galbebena skengama?',
          'Diagnostics': 'Diagnostics',
          'Internet Speed Check': 'Internetni ta•rakaniko niani',
          'Legal': 'Niamo pangchake dakani',
          'Open-Source Licenses': 'Open-Source Licenses',
          'Privacy': 'Privacy',
          'Cookie Preference': 'Cookie Preference',
          'Terms of Use': 'Jakkalanio pangchakanirang',
          'Help': 'Dakchakani',
          'Privacy Agreement': 'Privacy Agreement',
          'Hello Meghalaya customer service':
              'Hello Meghalaya customer service',
          'About': 'Iani bidingo talatani',
          'Your Preferred Language': 'Nang•ni jakkalna nangnikgipa ku•sik',
          'What ever they selected': 'Uamang jekon baseaha',
          'Select District': 'A•jako basebo',
          'Are you resident of Meghalaya ?': 'Na•a Meghalayao songdonggipama?',
          'terms and conditions': 'Niamrang aro pangchakanirang',
          'I am agree to ': 'Anga iako ku•chaka',
          'Privacy statement': 'Privacy statement',
          'Please Check Terms & Conditions':
              'Ka•sapae niamrang aro pangchakanirangko nibo',
          'Please check you network': 'Ka•sapae nang•ni networkko nibo',
          'See More': 'Niangkuani',
          'Stories': 'Golporang',
          'Continue Watching': 'Nianiko dakangkuani',
          'Recommend Movies': 'Filmrangko janapatbo',
          'Short Films': 'Kan•dikgipa filmrang',
          'Live Streaming': 'Live Streaming',
          'Most Watched Videos': 'Nibatgipa videorang',
          'Govt New Schemes': 'Sorkarini gital schemerang',
          'Live Stream': 'Live Stream',
          'Click on watch live': ' Watch live-ko sikdepbo',
          'Watch Live': 'Watch Live',
          'Live stream will start soon...':
              'Live stream dikdiksa ja•man a•bachenggen...',
          'Live Stream': 'Live Stream',
          'Recommend Short Films': 'Short Filmrangko janapatbo',
          'Most Watched Short Films': 'Manderangni nibatgipa short filmrang',
          'Action Movies': 'Action Movies',
          'Crime Thriller': 'Crime Thriller',
          'Romantic': 'Romantic',
          'Music Album': 'Music Album',
          'Music videos': 'Music videorang',
          'Trending Music': 'Trending Music',
          'Hot Music': 'Hot Music',
          "Please press back again to Exit":
              "Ianoni re•ongkatna gita sikdeptaibo",
          "Video Resolution Quality": "Video Resolution Quality",
          'Already Downloded': 'Download ka•manaha',
          'Influencer': 'Influencer',
          'Please turn on your Mobile Data': 'Nang•ni mobile datako on ka•bo',
          'Please turn on your Wifi': 'Nang•ni Wifiko on ka•bo',
          'Already Downloaded': 'Download ka•manaha',
          'Recommended Videos': 'Nina mesokatenggipa videorang',
          'Upload Statement': ' Statementko upload ka•bo',
          'No email': 'Email dongja',
          'Available': 'Donga',
          'Manage Profile': 'Profileko tariani',
          'Notifications': 'U•iatanirang',
          'Earnings': 'Man•anirang',
          'Start Watching': 'Nina a•bachengani',
          'Play Trailer': 'Trailerko watani',
          "HelloMegha": 'हेलो मेघालय',
          "Not Registered yet?": "पंजीकरण नहीं किया?",
          "Register": "पंजीकरण करवाना",
          "Reset Password": " पासवर्ड रीसेट करें",
          "Change Password": " पासवर्ड बदलें",
          "Create Account": ' नया अकाउंट बनाएँ  or खाता बनाएं',
          "Old password": " पुराना पासवर्ड",
          "Password": " पासवर्ड",
          "First Name": " प्रथम नाम",
          "Last Name": "उपनाम",
          "Email": " ईमेल",
          "User Name": "उपयोगकर्ता नाम",
          "Create Password": "पासवर्ड बनाएं",
          "New Password": "नया पासवर्ड",
          "Enter email or mobile number": "ईमेल या मोबाइल नंबर दर्ज करें",
          "Logout": " लॉग आउट",
          "EPIC": "ईपीआईसी",
          "Back to ": "वापस",
          "Back": "वापस ",
          "Home": " होम ",
          "Account": " खाता ",
          "Support": " सहायता ",
          "Email us": "हमें ईमेल करें",
          "Email": " ईमेल ",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Contact us": " हमसे संपर्क करें",
          "No Internet connection.": " इंटरनेट कनेक्शन नहीं है",
          "+91-": "+91-",
          "Edit Account details": " खाता विवरण संपादित करें",
          "Update Profile/Account": " प्रोफ़ाइल/खाता अपडेट करें ",
          "Enter your first name here": " अपना प्रथम नाम यहाँ दर्ज करें ",
          "Enter your last name here": " अपना उपनाम यहाँ दर्ज करें ",
          "Enter Password": " पासवर्ड डालें ",
          "Enter mobile number": " मोबाइल नंबर डालें ",
          "Verify OTP": "ओटीपी की पुष्टि करें",
          "Create new password": "नया पासवर्ड बनाएं",
          "Forgot password? Reset here": "पासवर्ड भूल गए? यहां रीसेट करें",
          "Tell me about yourself by signing up":
              "साइन अप करके अपने बारे में मुझे बताएं",
          "Login": "लॉग इन करें",
          "Forgot Password": "पासवर्ड भूल गए",
          "Send OTP": "ओटीपी भेजें",
          "Email OTP": " ईमेल ओटीपी ",
          "Resend OTP": " ओटीपी पुनः भेजें ",
          "Continue": " जारी रखें ",
          "Next": " अगला ",
          "Finish": " समाप्त ",
          "Full Name": " पूरा नाम ",
          "Mobile": " मोबाइल ",
          "Mobile Number": " मोबाइल नंबर ",
          "Choose Avatar": " अवतार चुनें ",
          "Please enter valid OTP": " कृपया मान्य ओटीपी डालें ",
          "CREATE ACCOUNT": 'नया अकाउंट बनाएँ  or खाता बनाएं',
          "Disclaimer": " अस्वीकरण ",
          "Forgot Password?": " पासवर्ड भूल गए?",
          "Yes": " हाँ ",
          "No": " नहीं ",
          "Are you sure, do you want to logout?":
              " क्या आप सुनिश्चित हैं, क्या आप लॉगआउट करना चाहते हैं?",
          "Select": " चयन करें ",
          "Existing user?": "मौजूदा उपयोगकर्ता?",
          "LOG IN": " लॉग इन करें ",
          "Please enter first name": " कृपया प्रथम नाम दर्ज करें ",
          "Please enter last name": " कृपया उपनाम दर्ज करें ",
          "Email required": " ईमेल (अनिवार्य)",
          "Password required": " पासवर्ड (अनिवार्य)",
          "Please enter a valid email address":
              " कृपया एक मान्य ईमेल पता दर्ज करें",
          "Password not matched": " पासवर्ड मेल नहीं खाता",
          "Enter valid password": "मान्य पासवर्ड दर्ज करें",
          "Please enter full name": "कृपया पूरा नाम दर्ज करें",
          "Please enter valid number": " कृपया वैध नंबर डालें",
          "OK": "ठीक है",
          "Edit and Update": "एडिट और अपडेट करें",
          "KYC Update": "केवाईसी अपडेट",
          "Update": "अपडेट करें",
          "Are you sure?": "क्या आप निश्चित हैं?",
          "Live will stop": "लाइव रुक जाएगा",
          "Cancel": "रद्द करें",
          "Exit": "बाहर निकलें",
          'Notifications': 'सूचनाएं',
          'No Internet connection found. Check your connection or try again':
              'कोई इंटरनेट कनेक्शन नहीं मिला। अपना कनेक्शन जांचें या फिर से कोशिश करें',
          'Please Verify\nYour': 'कृपया पुष्टि करेंअपना',
          'Enter the 4-digit code sent to':
              '4 अंकों का कोड दर्ज करें जिसे भेजा गया',
          'App Settings': 'ऐप सेटिंग्स',
          'Video Playback ': 'वीडियो प्लेबैक',
          'Downloads': 'डाउनलोड',
          'Wi-Fi Only': 'केवल वाई-फाई',
          'Let\'s Get ': 'प्राप्त करें',
          'Started': 'शुरू',
          'Let\'s Get Started': 'आइए शुरू करें',
          'My List': 'मेरी सूची',
          'Password must contain 1 special 1 capital and 1 small character':
              'पासवर्ड में 1 विशेष, 1 बड़ा अक्षर और 1 छोटा वर्ण होना चाहिए ',
          'Please check your network': 'कृपया अपना नेटवर्क जांचें',
          'Stories': 'कहानियां',
          'Continue Watching': 'देखना जारी रखें',
          'Today\'s Top 10 Picks': 'आज के शीर्ष 10 चयन',
          'Winner of': 'के विजेता',
          'What is happening in universe': 'ब्रह्मांड में क्या हो रहा है',
          'Amrit Kumar': 'अमृत कुमार ',
          'Quiz': 'प्रश्नोत्तरी',
          'Monthly Quiz': 'मासिक प्रश्नोत्तरी',
          'Weekly Quiz': 'साप्ताहिक प्रश्नोत्तरी',
          'Hot Videos': 'हॉट वीडियो',
          'Scheme Videos': 'योजना वीडियो',
          'Recommend Videos': 'अनुशंसित वीडियो',
          'Live Stream': 'लाइव स्ट्रीम',
          'Click on watch live': 'लाइव देखने के लिए क्लिक करें',
          'Watch Live': 'लाइव देखें',
          'Live stream will start soon...': 'लाइव स्ट्रीम जल्द ही शुरू होगा...',
          'Get Start': 'आरंभ करें',
          'Short Films': 'लघु फिल्म',
          'Go': 'जाना',
          'Strings.stories': 'स्ट्रिंग्स.स्टोरीज़',
          'Influncers videos': 'इन्फ्लुएंसर वीडियो',
          'Continue Watching': 'देखना जारी रखें',
          'Today\'s Top 10 Picks': 'आज के शीर्ष 10 चयन',
          'Comedy': 'कॉमेडी',
          'Horror': 'हॉरर',
          'Romantic': 'रोमांटिक',
          'Music videos': 'म्यूजिक वीडियोज',
          'Music Artists': 'संगीत कलाकार',
          'Music Album ': 'संगीत एल्बम',
          'Trending Music': 'ट्रेंडिंग म्यूजिक',
          'Hot Music': 'हॉट म्यूजिक',
          'Music': 'संगीत',
          '80 Music': '80 के दशक का संगीत',
          'Coming Soon': 'जल्द आ रहा है',
          'No Downloaded Available': 'कोई डाउनलोड उपलब्ध नहीं',
          'Are you sure? you want to to delete':
              'क्या आप सुनिश्चित हैं? आप डिलीट करना चाहते हैं?',
          'Delete': 'डिलीट',
          'No Downloaded Movies available':
              'कोई डाउनलोड की गई फिल्में उपलब्ध नहीं हैं',
          ' All  ': '  सब ',
          'Movies': 'फिल्में',
          'Music Video': ' म्यूजिक वीडियो',
          'Videos': 'वीडियो',
          'KYC ': 'केवाईसी',
          'Let\'s Get ': 'प्राप्त करें',
          'Bank Statement': 'बैंक स्टेटमेंट',
          'More': 'और',
          'Available': 'उपलब्ध',
          'Delete account': 'डिलीट एकाउंट',
          'Are you sure, you want to delete the Account?':
              'क्या आप सुनिश्चित हैं, आप खाता डिलीट करना चाहते हैं?',
          'Premium | U/A 7+': 'प्रीमियम | यू/ए 7+',
          '2019 . Sci-fi . Action': '2019। साइंस फिक्शन। ',
          'Watch List': 'देखें सूची',
          'Cast': 'कास्ट',
          'Directer & Writers': 'निर्देशक और लेखक',
          'Similar movies': 'मिलती-जुलती फिल्में',
          'Premium | U/A 11+': 'प्रीमियम | यू/ए 11+',
          'No movie available': 'कोई फिल्म उपलब्ध नहीं',
          'Similar content': 'समान कंटेंट',
          'Filter': 'फ़िल्टर',
          'Streaming': 'स्ट्रीमिंग',
          'Click on watch live': 'लाइव देखने के लिए क्लिक करें',
          'Withdraw ': 'वापस लेना',
          'All Transactions': 'सभी लेन - देन',
          'Order ID': 'ऑर्डर आईडी',
          'Name': 'नाम',
          'Transaction Id': 'ट्रांजैक्शन आईडी',
          'Processing': 'प्रोसेसिंग',
          'Are you sure?': 'क्या आप सुनिश्चित हैं?',
          'Coins will convert into amount': 'सिक्के रकम में बदल जाएंगे',
          'Can\'t withdraw': 'वापसी नहीं कर सकता',
          'Don\'t have amount': 'राशि नहीं है'
        },
        'en_kashi': {
          "HelloMegha": "Khublei Megha",
          "Not Registered yet?": "Ym pat dep registar?",
          "Register": "Registar",
          "Reset Password": "shna biang ka password ",
          "Change Password": "Kylliang ka password",
          "Create Account": "Ban Shna Account",
          "Old password": "Ka Password barim",
          "Password": "Ka Password",
          "First Name": "Kyrteng",
          "Last Name": "Ka jait",
          "Email": "Ka Email",
          "User Name": "Ka Kyrteng ban buh",
          "Create Password": "Shna ia ka password",
          "New Password": "Ka Password thymmai",
          "Enter email or mobile number":
              "Sa leit ha ka email lane da u mobile nombar",
          "Logout": "Logout",
          "EPIC": "EPIC",
          "Back to ": "Sa leit biang",
          "Back": "shadien",
          "Home": "Leit ha ing",
          "Account": "Account",
          "Support": "Bankyrshan",
          "Email us": "Email sha ngi",
          "Email": "Email",
          "Confirm Password": "sa ai ka Password ",
          "Contact us": "Ban kynjoh sha ngi",
          "No Internet connection.": "Lada ym don Internet connection...",
          "+91-": "+91-",
          "Edit Account details": "pyndap ia ki jingdonkam baroh",
          "Update Profile/Account": "Ban pynbiang ia ki jingpynithuh ba pura",
          "Enter your first name here": "Ai ia ka Kyrteng hangne",
          "Enter your last name here": "Sa pyndap ia ka jait hangne ",
          "Enter Password": "Sa ai ka password",
          "Enter mobile number": "sa ai u mobile nombar",
          "Verify OTP": "pynshisha OTP",
          "Create new password": "Shna ia ka password thymmai",
          "Forgot password? Reset here":
              "Lah klet password? Shna da kawei ka password hangne ",
          "Tell me about yourself by signing up":
              "ban sign up batai shaphang jong phi",
          "Login": "Sa Login",
          "Forgot Password": "leit pat ha ka Forgot Password",
          "Send OTP": "Sa phah OTP",
          "Email OTP": "Ha Email OTP",
          "Resend OTP": "Sa phah biang OTP",
          "Continue": "Sa Continue",
          "Next": "Hadien",
          "Finish": "Da dep ",
          "Full Name": "Ka Kyrteng ba pura bad ka jait",
          "Mobile": "Mobile",
          "Mobile Number": " U Mobile Nombar",
          "Choose Avatar": "sa leit ha ka Choose Avatar",
          "Please enter valid OTP": "sngewbha sa ai ia ka OTP kaba biang",
          "CREATE ACCOUNT": "Shna da ka ACCOUNT",
          "Disclaimer": "Ka jingmaham",
          "Forgot Password?": "Lah klet Password?",
          "Yes": "Hooid ",
          "No": "Em",
          "Are you sure, do you want to logout?":
              "Phi la tikna ba kwah ban logout?",
          "Select": "Sa Select",
          "Existing user?": " Ba lah ju pyndonkam teng?",
          "LOG IN": " Sa LOG IN",
          "Please enter first name": "Sngewbha ban pyndap ia ka Kyrteng ",
          "Please enter last name": "Sngewbha ban pyndap ia ka jait",
          "Email required": "Donkam ia ka email ",
          "Password required": "Donkam ia ka password",
          "Please enter a valid email address":
              "Sngewbha ban ai ia ka email ba dang long",
          "Password not matched": "Ka Password kam iahap ",
          "Enter valid password": "ai ia ka password ba dang treikam",
          "Please enter full name": "Sngewbha ban ai ia ka Kyrteng  ba pura",
          "Please enter valid number":
              " Sngewbha ban ai ia u nombar ba dang long",
          "OK": "OK",
          "Edit and Update": "pynkylla bad sa Update",
          "KYC Update": "KYC Update",
          "Update": "Update",
          "Are you sure?": "Phi lah tikna?",
          "Live will stop": "ka Live kan kut noh",
          "Cancel": "Cancel",
          "Exit": "Exit",
          'Notifications': 'jingpyntip ',
          'No Internet connection found. Check your connection or try again':
              'Ym lah ban connect ia ka Internet. Peit bha ia ka connection sa pyrshang biang',
          'Please Verify\nYour': 'Please Verify\nYour',
          'Enter the 4-digit code sent to':
              'Sa ai sawtylli ka numbar code sa phah sha',
          'App Settings': ' App Settings',
          'Video Playback ': 'tem biang ia ka video',
          'Downloads': 'Sa Downloads',
          'Wi-Fi Only': 'Tang ha Wi-Fi',
          'Let\'s Get ': 'Let\'s Get ',
          'Started': 'Lah sdang',
          'My List': 'Ka List jong nga',
          'Password must contain 1 special 1 capital and 1 small character':
              'Ka Password ka dei ban don Wei ba kyrpang, U wei dak heh bad wei u dak rit.',
          'Please check your network': 'Sngewbha peit ia ka network',
          'Please check your network': 'sngewbha ban peit ia ka network',
          'Stories': 'Ki Stories',
          'Continue Watching': 'Sa dang bteng ban peit ',
          'Today\'s Top 10 Picks': 'Ki Top 10 ba mynta sngi ',
          'Winner of': 'U Nongjop jong',
          'What is happening in universe': 'Kaei ka jingjia ha ka pyrthei',
          'Amrit Kumar': 'Amrit Kumar',
          'Quiz': 'jingkyli',
          'Monthly Quiz': 'Ki jingkyli ba man u bnai ',
          'Weekly Quiz': 'jingkyli ba man ka taiew',
          'Hot Videos': 'ki video ba kham iaid bha',
          'Scheme Videos': 'Scheme Videos',
          'Recommend Videos': 'Ki Videos ba lah mang na bynta jong phi ',
          'Live Stream': 'Ka live stream video',
          'Click on watch live': 'Sa khniot ha watch live ',
          'Watch Live': ' Sa Watch Live',
          'Live stream will start soon...':
              'Ka live stream kan sa sdang sa shiphang...',
          'Get Start': 'sdang noh',
          'Short Films': 'ki phlim lyngkot ',
          'Go': 'Leit ',
          'Strings.stories': 'stories',
          'Influncers videos': 'ki nongpynshong shit / ki nongkren ba tbit',
          'Continue Watching': 'Bteng ban peit',
          "Today's Top 10 Picks": " Ki 10 tylli ki ba lah ban  jied mynta sngi",
          'Comedy': 'jingpyn rkhie/samrkhie',
          'Horror': 'jingpyntieng',
          'Romantic': 'jingieid',
          'Music videos': 'ki video jingrwai',
          'Music Artists': 'U nongrwai',
          'Music Album ': 'Album jingrwai',
          'Trending Music': 'jingrwai ba iaid iew bha',
          'Hot Music': 'jingrwai ba shongshit',
          'Music': 'jingrwai ',
          '80 Music': 'jingrwai ha ki snem 80',
          'Comming Soon': 'Ki ban sa mih ',
          'No Downloaded Available': 'Ym lah ban download',
          'Are you sure? you want to to delete':
              'Phi lah tikna? Phi kwah ban delete',
          'Delete': 'Delete',
          'No Downloaded Movies available': 'Ym don phlim ban download',
          ' All  ': '  Baroh  ',
          'Movies': 'Phlim',
          'Music Video': ' videos jingrwai',
          'Videos': 'Videos',
          'KYC ': 'KYC ',
          'Let\'s Get ': 'Ia ngin sdang',
          'Bank Statement': 'Bank Statement',
          'More': 'shuh shuh',
          'Available': 'Ki don ',
          'Delete account': ' Ban pynduh / pyndam noh ia ka account',
          'Are you sure, you want to delete the Account?':
              'Phi lah tikna, phi kwah pyndam noh ia ka Account?',
          'Premium | U/A 7+': 'Premium | U/A 7+',
          '2019 . Sci-fi . Action': '2019 . Sci-fi . Action',
          'Watch List': 'ki list ban peit',
          'Cast': 'Ki nongak ',
          'Directer & Writers': 'u direktor bad Nongthoh',
          'Similar movies': 'Ki movies ba ïasyriem',
          'Premium | U/A 11+': 'Premium | U/A 11+',
          'No movie available': 'ym don phlim ',
          'Similar content': 'ki content ba ïa syriem',
          'Filter': 'Filter',
          'Streaming': 'Streaming',
          'Click on watch live': 'Sa khñiot ha watch live',
          'Withdraw ': 'Pyndam',
          'All Transactions': 'baroh ki Transactions',
          'Order ID': 'Order ID',
          'Name': 'Kyrteng',
          'Transaction Id': 'Transaction Id',
          'Processing': 'Dang iaid ',
          'Are you sure?': ' Phi lah tikna ?',
          'Coins will convert into amount':
              'Ban pynkylla ia ki points sha ka pisa',
          'Can\'t withdraw': 'ym lah ban Sei ',
          'Don\'t have amount': 'Bym don tyngka',
          'Similar movies': 'Ki phlim ba ia syriem',
          'Music': 'Ki Jingput jingtem',
          'Password must contain 1 special 1 capital and 1 small character':
              'Ka Password ka dei ban don uwei u dak ba kyrpang, uwei  u dak heh, bad uwei u dak rit',
          'Password required min length 7':
              'Ka password ka dei ban don kumba 7 tylli ki dak',
          'Request cancelled': 'Pyndam ia ka jingkyrpad',
          'Server unreachable': 'Ym lap ia ka server',
          'Something went wrong': 'Don ka jingbakla',
          'Please try again': 'Sngewbha pyrshang biang',
          'All as playlist': 'Baroh kum ki playlist',
          'Now Playing': 'Dang tem mynta',
          'Play All': 'Tem lut Baroh',
          'Your score': 'Ka jingkhein jong phi',
          "Looks like you have answered one or more questions incorrectly. Try your luck with other games.":
              "Phi la bakla jubab ia kawei lane bun tylli ki jingkylli. Pyrshang noh da kiwei ki jingialehkai",
          'Play & Collect Coins': 'Lehkai bad lum ia ki Pisa Naia',
          'Terms & Conditions': 'Ki kyndon',
          "Let's Play Quiz": "To ngin ia lehkai Kyntip",
          "Lets Start Quiz": "To ngin sdang ka jingialehkai kyntip",
          'Winners': 'Ki Nongjop',
          'Weekly Winners': 'Ki Nongjop jong kane ka taiew',
          'Filter': 'Filter',
          'Winner name': 'Kyrteng jong ki Nonjop',
          'Monthly Winners': 'Ki Nongjop jong u bnai',
          'Mobile number is required': 'Donkam ia ka mobile number',
          'Mobile number must be 10 digits':
              'U Mobile number u dei ban don 10 tylli ki dak',
          'Enter 10 digits mobile': 'Thoh ia u mobile number ba 10 dak',
          'Recommend Music Videos':
              'Ki Video jong ki jingrwai ba lah jied na ka bynta jong phi',
          "Music Video": "Ki video jingrwai",
          'Notifications': 'Ki Jinpyntip',
          'Language': 'Ka Ktien',
          'Enter the 5 digit code sent to':
              'Thoh ia 5 tylli u code numbar ba phah sha',
          'Please enter phone number': 'Sngewbha thoh ia u phone number',
          'Date Of Birth is required': 'Donkam ia ka tarik sngikha jong phi',
          "Select Your City": "Jied ia ka Shnong jong phi",
          'City is required': 'Donkam ia ka Shnong jong phi',
          "View KYC": "Peit ia ka KYC",
          'Upload': 'Upload',
          '* required': '* donkam',
          'Account Number': 'U Account Number',
          'Enter Account Number': 'Thoh ia u Account Number',
          'Enter IFSC Code': 'Thoh ia u IFSC Code',
          'AADHAR Number': 'AADHAR Number',
          'IFSC Code': 'IFSC Code',
          'Voter ID': 'Voter ID',
          'Enter Voter ID': 'Thoh ia u Voter ID',
          'Bank Name': 'Ka kyrteng jong ka bank',
          'Enter Bank name': 'Thoh ia ka kyrteng jong ka bank',
          'Update Kyc': 'Pynthymmai ia ka Kyc',
          "Please Fill up all the details":
              "Sngewbha thoh lut baroh ki jingtip",
          'App Settings': 'Ka Settings jong ka App',
          'Video Playback': 'Sdang biang ia ka video ',
          'Cellular Data Usage': 'Ka jingpyndonkam jong ka Cellular Data',
          'Allow Notifications': 'Shah ia ki jingpyntip',
          'Customize in Settings': 'Pynkylla hapoh ka Settings',
          'Download Video Quality':
              'Ka jinglong jong ka video ba la dep download',
          'Select Download Video Quality':
              'Jied ia ka jinglong jong ka video ba la dep download',
          'Play Video Quality': 'Ka jinglong jong ka video ban tem',
          "Select Play Video Quality":
              " Jied ia ka jinglong jong ka video ban tem",
          'Download Location': 'Ka jaka buh jong kaei ba la download',
          "Select Download Location":
              " Jied ia ka jaka buh jong kaei ba la download ",
          'Delete All Downloads': 'Weng noh ia baroh kiba la download',
          'Are you sure? you want to to delete all download?':
              'Phi la tikna ba phi kwah weng noh ia baroh kiba la download?',
          'Diagnostics': 'Diagnostics',
          'Internet Speed Check': 'Peit ia ia jingsted jong ka bor Internet',
          'Legal': 'Ba iadei bad ka ain',
          'Open-Source Licenses': 'Open-Source Licenses',
          'Privacy': 'Privacy',
          'Cookie Preference': 'Cookie Preference',
          'Terms of Use': 'Ka jingbatai kumno ban pyndonkam',
          'Help': 'Jingiarap',
          'Privacy Agreement': ' Ka jingiakut ban long buhrieh',
          'Hello Meghalaya customer service':
              'Ka Hello Meghalaya customer service',
          'About': 'About',
          'Your Preferred Language': 'Ka Ktien ba phi nang ban kren',
          'What ever they selected': 'Kaei kaba ki la jied ',
          'Select District': 'Jied ka Distrik',
          'Are you resident of Meghalaya ?':
              'Phi dei nongshong shnong jong ka Meghalaya?',
          'terms and conditions': 'Ki kyndon',
          'I am agree to ': 'Nga la mynjur ban',
          'Privacy statement': 'Privacy statement',
          'Please Check Terms & Conditions': 'Sngewbha pule ia ki kyndon',
          'Please check you network': 'Sngewbha peit ia ka network jong phi',
          'See More': 'Peit shuh shuh',
          'Stories': 'Stories',
          'Continue Watching': 'Bteng ban peit',
          'Recommend Movies': ' Ki phlim ba lah jied na ka bynta jong phi ',
          'Short Films': 'Ki Phlim lyngkot',
          'Live Streaming': 'Ka Live Streaming',
          'Most Watched Videos': 'Ki video kiba iaid iew',
          'Govt New Schemes': 'Ki skim thymmai jong ka Sorkar',
          'Live Stream': 'Ka Live Stream',
          'Click on watch live': ' Khniot ha watch live ',
          'Watch Live': 'Peit ia ka Live',
          'Live stream will start soon...':
              ' Ka live stream kan sa sdang shen....',
          'Live Stream': 'Ba Pyni mynta',
          'Recommend Short Films':
              ' Ki phlim lyngkot ba lah jied na ka bynta jong phi ',
          'Most Watched Short Films': 'Ki phlim lyngkot kiba iaid iew',
          'Action Movies': 'Ki Phlim Iashoh Iamai',
          'Crime Thriller': 'Ki Phlim Kam Sniew',
          'Romantic': 'Jingieid',
          'Music Album': 'Ki album jingrwai',
          'Music videos': 'Ki video jingrwai',
          'Trending Music': 'Ki jingrwai ba iaid iew',
          'Hot Music': 'Ki jingrwai ba kham shongshit',
          "Please press back again to Exit":
              "Sngewbha khnoit biang ban Mih noh",
          "Video Resolution Quality": "Video Resolution Quality",
          'Already Downloded': 'Ki ba la dep download lypa',
          'Influencer': 'Ki Influencer',
          'Please turn on your Mobile Data':
              'Sngewbha plie ia ka Mobile Data jong phi',
          'Please turn on your Wifi': 'Sngewbha plie ia ka Wifi jong phi',
          'Already Downloaded': ' Ki ba la dep download lypa ',
          'Recommended Videos': ' Ki Video ba lah jied na ka bynta jong phi ',
          'Upload Statement': 'Upload Statement',
          'No email': 'Ym don email',
          'Available': 'Don',
          'Manage Profile': ' Pynbeit ki jingtip jong la jong ',
          'Notifications': 'Ki Jingpyntip',
          'Earnings': 'Ki Jingkamai',
          'Start Watching': 'Sdang Peit',
          'Play Trailer': 'Peit ia ka Trailer'
        },
        'en_pnar': {
          "HelloMegha": "HelloMegha",
          "Not Registered yet?": "Ym pu em pynpsiah prytuit?",
          "Register": "Pynpsiah prytuit",
          "Reset Password": "Pynthymme ia u Password",
          "Change Password": "Kylliang ia uPassword",
          "Create Account": "Chna Account",
          "Old password": " Password wa rim",
          "Password": " U Password",
          "First Name": "I Prytuit",
          "Last Name": "I Jait",
          "Email": "Ka Email",
          "User Name": "I Prytuit",
          "Create Password": "Chna Password",
          "New Password": "Password Thymme",
          "Enter email or mobile number":
              "Thoh ia ka email lane u phone number",
          "Logout": "Logout",
          "EPIC": "Ka EPIC",
          "Back to ": "Back to ",
          "Back": "Back",
          "Home": "Home",
          "Account": "Account",
          "Support": "Support",
          "Email us": "Email cha i",
          "Email": "Ka Email",
          "Confirm Password": "Pyntikna ia u Password",
          "Contact us": "Pynsniaw cha i",
          "No Internet connection...": "Ym em Internet connection...",
          "+91-": "+91-",
          "Edit Account details": "Pynkylla ia kiwa em hapoh Account",
          "Update Profile/Account": "Pynbeit ia ka Profile/Account",
          "Enter your first name here": "Thoh iei prytuit iong phi heini",
          "Enter your last name here": " Thoh iei jait iong phi heini ",
          "Enter Password": "Thoh ia u Password",
          "Enter mobile number": "Thoh ia u mobile number",
          "Verify OTP": "Pyntikna ia u OTP",
          "Create new password": "Chna password thymme",
          "Forgot password? Reset here":
              "Da myllin phi ia u password? Pynthymme heini",
          "Tell me about yourself by signing up":
              "Khana ianga chiphang iong phi dei wa pynpsiah prytuit",
          "Login": "Login",
          "Forgot Password": "Da myllin ia u password ",
          "Send OTP": "Phah ia u OTP",
          "Email OTP": "Email ia u OTP",
          "Resend OTP": "Phah biang ia u OTP",
          "Continue": "Continue",
          "Next": "Next",
          "Finish": "Finish",
          "Full Name": "I Prytuid",
          "Mobile": "Ka Mobile",
          "Mobile Number": "U Mobile Number",
          "Choose Avatar": "Jied ia u Avatar iong phi",
          "Please enter valid OTP": "Thoh ia u OTP wa toh",
          "CREATE ACCOUNT": "CHNA ACCOUNT",
          "Disclaimer": "Ka Jingmana",
          "Forgot Password?": " Da myllin phi ia u password?",
          "Yes": "Hao",
          "No": "Ahoh",
          "Are you sure, do you want to logout?":
              'Da tikna phi, kwah phi u logout noh?',
          "Select": "Select",
          "Existing user?": "Da juh pynemkam phi mynchwa?",
          "LOG IN": "LOG IN",
          "Please enter first name": " Thoh iei prytuit iong phi heini ",
          "Please enter last name": " Thoh iei jait iong phi heini ",
          "Email required": "Emkam ia ka email",
          "Password required": "Emkam ia u password",
          "Please enter a valid email address": "Thoh iei thaw sah iong phi",
          "Password not matched": "Ym iahap u password wa thoh phi",
          "Enter valid password": "Thoh ia u password wa toh",
          "Please enter full name": "Thoh iei prytuit iong phi",
          "Please enter valid number": "Thoh ia u phone number wa toh",
          "OK": "OK",
          "Edit and Update": "Pynkylla wei Pynbeit",
          "KYC Update": "Pynbeit ia ka KYC",
          "Update": "Pynbeit",
          "Are you sure ?": "Da tikna phi ?",
          "Live will stop": "Daw sangeh ka live",
          "Cancel": "Cancel",
          "Exit": "Exit",
          'Notifications': 'Notifications',
          'No Internet connection found. Check your connection or try again':
              'Ym chem ia Internet connection. Peit ia ka connection iong phi lane pyrchang biang',
          'Please Verify\nYour': 'Please Verify\nYour',
          'Enter the 4 digit code sent to':
              'Thoh ia u code 4 digit wa da phah cha',
          'App Settings': 'App Settings',
          'Video Playback': 'Video Playback',
          'Downloads': 'Downloads',
          'Wi-Fi Only': 'Wi-Fi Only',
          'Let\'s Get ': 'Let\'s Get ',
          'Started': 'Started',
          'My List': 'My List',
          'Password must contain 1 special 1 capital and 1 small character':
              'U password toh u em u 1 special, 1 capital, wa 1 small character',
          'Please check you network': 'Sniawbha peit ia ka network iong phi',
          'Stories': 'Stories',
          'Continue Watching': 'Sdang biang u peit',
          'Today\'s Top 10 Picks': 'Ki Top 10 wa da jied kyrpang ynne ka sngi',
          'Winner of': 'Ki nongjop iong ka',
          'What is happening in universe': 'Yi wa jia hapoh ka universe',
          'Amrit Kumar': 'Amrit Kumar',
          'Quiz': 'Ka Quiz',
          'Monthly Quiz': 'Ka Quiz iong bnai',
          'Weekly Quiz': 'Ka Quiz iong taiaw',
          'Hot Videos': 'Ki video wa rap chongchit',
          'Scheme Videos': 'Ki video iong ki skim',
          'Recommend Videos': 'Pynioo ia ki video thymme',
          'Live Stream': 'Ka Live Stream',
          'Click on watch live': 'Khnion ha watch live',
          'Watch Live': 'Watch Live',
          'Live stream will start soon...':
              'Daw sdang ka Live stream sa chibet chipor',
          'Get Start': 'Get Start',
          'Short Films': 'Ki Short Films',
          'Go': 'Go',
          'Strings.stories': 'Ki Stories',
          'Influncers videos': 'Ki video iong ki Influencers',
          'Continue Watching': ' Sdang biang u peit ',
          'Today\'s Top 10 Picks':
              ' Ki Top 10 wa da jied kyrpang ynne ka sngi ',
          'Comedy': 'Comedy',
          'Horror': 'Horror',
          'Romantic': 'Romantic',
          'Music videos': 'Ki video iong ki Sur',
          'Music Artists': 'Ki Nongrwai/Nongtem',
          'Music Album ': 'Ki album Sur ',
          'Trending Music': 'Ki Sur wa mih cha khmat',
          'Hot Music': 'Ki Sur wa rap chongchit ',
          'Music': 'Ki Sur',
          '80 Music': 'Ki Sur na u snem 80',
          'Comming Soon': 'Kiwa daw pynmih',
          'No Downloaded Available': 'Ym em kiwa dep download',
          'Are you sure? you want to to delete':
              'Da tikna phi kwah phi u delete noh?',
          'Delete': 'Delete',
          'No Downloaded Movies avilable': 'Ym em ki phlim kiwa dep download',
          '  All  ': '  All  ',
          'Movies': 'Phlim',
          'Music Video': ' Ki video iong ki Sur ',
          'Videos': 'Ki Video',
          'KYC ': 'KYC ',
          'Let\'s Get ': 'Let\'s Get ',
          'Bank Statement': 'Ka Bank Statement',
          'More': 'More',
          'Available': 'Available',
          'Delete account': 'Delete ia ka account',
          'Are you sure, you want to delete the Account?':
              ' Da tikna phi kwah phi u delete noh ia ka account?',
          'Premium | U/A 7+': 'Premium | U/A 7+',
          '2019 . Sci-fi . Action': '2019 . Sci-fi . Action',
          'Watch List': 'Ka Watch List',
          'Cast': 'Ki Nongchimbynta',
          'Directer & Writers': 'Ki director wa ki Nongthoh',
          'Similar movies': 'Ki phlim kiwa rap sariem',
          'Premium |  U/A 11+': 'Premium |  U/A 11+',
          'No movie available': 'Ym em phlim',
          'Similar content': 'Kiwi taewon ki wa rap sariem',
          'Filter': 'Filter',
          'Streaming': 'Streaming',
          'Click on watch live': 'Khnion ha watch live',
          'Withdraw ': 'Sai noh',
          'All Transactions': 'Waroh ki Transactions',
          'Order ID': 'U Order ID',
          'Name': 'Prytuit',
          'Transaction Id': 'U Transaction Id',
          'Processing': 'Dang pynkhreh',
          'Are you sure?': 'Da tikna phi?',
          'Coins will convert into amount':
              'Ki coins daw kylla ki cha ka poisa',
          'Can\'t withdraw': 'Ym ye u sai',
          'Don\'t have amount': 'Ym em poisa'
        },
        'en_US': {
          'robotoMedium ': 'Roboto-Medium',
          'robotoRegular ': 'Roboto-Medium',
          'notRegistered ': 'Not Registered yet?',
          'register ': 'Register',
          'resetPassword ': 'Reset Password',
          'changePassword ': 'Change Password',
          'createAccount ': 'Create Account',
          'oldPassword ': 'Old password',
          'password ': 'Password',
          'firstName ': 'First Name',
          'lastName ': 'Last Name',
          'emailOrMobile ': 'Email or Mobile Number',
          'userName ': 'User Name',
          'createPassword ': 'Create Password',
          'newPassword ': 'New Password',
          'enterEmailMobileHere ': 'Enter email or mobile number',
          'logout ': 'Logout',
          'epic ': 'EPIC',
          'backTo ': 'Back to ',
          'backTxt ': 'Back',
          'home ': 'Home',
          'account ': 'Account',
          'support ': 'Support',
          'emailUs ': 'Email us',
          'email ': 'Email',
          'confirmPassword ': 'Confirm Password',
          'contactUs ': 'Contact us',
          'noInternetConnection ': 'No Internet connection...',
          'contactNumber ': '+91-',
          'editAccountDetails ': 'Edit Account details',
          'updateProfileAccount ': 'Update Profile/Account',
          'enterYourFastNameHere ': 'Enter your first name here',
          'enterYourLastNameHere ': 'Enter your last name here',
          'enterPassword ': 'Enter Password',
          'enterMobileNumber ': 'Enter mobile number',
          'verifyOTP ': 'Verify OTP',
          'createNewPassword ': 'Create new password',
          'forgotPasswordResetHere ': 'Forgot password? Reset here',
          'tellMeAboutYourself ': 'Tell me about yourself by signing up',
          'login ': 'Login',
          'forgotPass ': 'Forgot Password',
          'sendOTP ': 'Send OTP',
          'emailOTP ': 'Email OTP',
          'resendOTP ': 'Resend OTP',
          'continueTxt ': 'Continue',
          'nextTxt ': 'Next',
          'finishTxt ': 'Finish',
          'fullName ': 'Full Name',
          'mobile ': 'Mobile',
          'mobileNumber ': 'Mobile Number',
          'chooseAvatar ': 'Choose Avatar',
          'pleaseEnterValidOTP ': 'Please enter valid OTP',
          'createAccountCaps ': 'CREATE ACCOUNT',
          'disclaimer ': 'Disclaimer',
          'forgotPassword ': 'Forgot Password?',
          'yes ': 'Yes',
          'no ': 'No',
          'areYouSureDoYou ': 'Are you sure, do you want to logout?',
          'select ': 'Select',
          'existingUser ': 'Existing user?',
          'logIn ': 'LOG IN',
          'pleaseEnterFirstName ': 'Please enter first name',
          'pleaseEnterLastName ': 'Please enter last name',
          'mailRequired ': 'Email required',
          'passwordRequired ': 'Password required',
          'pleaseEnterAValidEmailAddress ':
              'Please enter a valid email address',
          'passwordNotMatch ': 'Password not matched',
          'enterValidPassword ': 'Enter valid password',
          'pleaseEnterFullName ': 'Please enter full name',
          'pleaseEnterValidNumber ': 'Please enter valid number',
          'ok ': 'OK',
          'editAndUpdate ': 'Edit and Update',
          'kycUpdate ': 'KYC Update',
          'update ': 'Update',
          'wifiOnly ': 'Wi-Fi Only',
          'mobileData ': 'Mobile Data',
          'wifiAndMobileDataBoth ': 'Wi-Fi and Mobile Data both',
          'Cast': 'Cast',
          "Short film": "Short film",
          'Similar movies': 'Similar movies',
          'Music': 'Music',
          'Password must contain 1 special 1 capital and 1 small character':
              'Password must contain 1 special 1 capital and 1 small character',
          'Password required min length 7': 'Password required min length 7',
          'Request cancelled': 'Request cancelled',
          'Server unreachable': 'Server unreachable',
          'Something went wrong': 'Something went wrong',
          'Please try again': 'Please try again',
          'All as playlist': 'All as playlist',
          'Now Playing': 'Now Playing',
          'Play All': 'Play All',
          'Your score': 'Your score',
          "Looks like you have answered one or more questions incorrectly. Try your luck with other games.":
              "Looks like you have answered one or more questions incorrectly. Try your luck with other games.",
          'Play & Collect Coins': 'Play & Collect Coins',
          'Terms & Conditions': 'Terms & Conditions',
          "Let's Play Quiz": "Let's Play Quiz",
          "Lets Start Quiz": "Lets Start Quiz",
          'Winners': 'Winners',
          'Weekly Winners': 'Weekly Winners',
          'Filter': 'Filter',
          'Winner name': 'Winner name',
          'Monthly Winners': 'Monthly Winners',
          'Mobile number is required': 'Mobile number is required',
          'Mobile number must be 10 digits': 'Mobile number must be 10 digits',
          'Enter 10 digits mobile': 'Enter 10 digits mobile',
          'Recommend Music Videos': 'Recommended Music Videos',
          "Music Video": "Music Video",
          'Notifications': 'Notifications',
          'Language': 'Language',
          'Enter the 5 digit code sent to': 'Enter the 5 digit code sent to',
          'Please enter phone number': 'Please enter phone number',
          'Date Of Birth is required': 'Date Of Birth is required',
          "Select Your City": "Select Your City",
          'City is required': 'City is required',
          "View KYC": "View KYC",
          'Upload': 'Upload',
          '* required': '* required',
          'Account Number': 'Account Number',
          'Enter Account Number': 'Enter Account Number',
          'Enter IFSC Code': 'Enter IFSC Code',
          'AADHAR Number': 'AADHAR Number',
          'IFSC Code': 'IFSC Code',
          'Voter ID': 'Voter ID',
          'Enter Voter ID': 'Enter Voter ID',
          'Bank Name': 'Bank Name',
          'Enter Bank name': 'Enter Bank name',
          'Update Kyc': 'Update Kyc',
          "Please Fill up all the details": "Please Fill up all the details",
          'App Settings': 'App Settings',
          'Video Playback': 'Video Playback',
          'Cellular Data Usage': 'Cellular Data Usage',
          'Allow Notifications': 'Allow Notifications',
          'Customize in Settings': 'Customize in Settings',
          'Download Video Quality': 'Download Video Quality',
          'Select Download Video Quality': 'Select Download Video Quality',
          'Play Video Quality': 'Play Video Quality',
          "Select Play Video Quality": "Select Play Video Quality",
          'Download Location': 'Download Location',
          "Select Download Location": "Select Download Location",
          'Delete All Downloads': 'Delete All Downloads',
          'Are you sure? you want to to delete all download?':
              'Are you sure? you want to to delete all download?',
          'Diagnostics': 'Diagnostics',
          'Internet Speed Check': 'Internet Speed Check',
          'Legal': 'Legal',
          'Open-Source Licenses': 'Open-Source Licenses',
          'Privacy': 'Privacy',
          'Cookie Preference': 'Cookie Preference',
          'Terms of Use': 'Terms of Use',
          'Help': 'Help',
          'Privacy Agreement': 'Privacy Agreement',
          'Hello Meghalaya customer service':
              'Hello Meghalaya customer service',
          'About': 'About',
          'Your Preferred Language': 'Your Preferred Language',
          'Your Preffered Language': 'Your Preffered Language',
          'Select District': 'Select District',
          'Are you resident of Meghalaya ?': 'Are you resident of Meghalaya ?',
          'terms and conditions': 'terms and conditions',
          'I am agree to ': 'I am agree to ',
          'Privacy statement': 'Privacy statement',
          'Please Check Terms & Conditions': 'Please Check Terms & Conditions',
          'Please check you network': 'Please check you network',
          'See More': 'See More',
          'Stories': 'Stories',
          'Continue Watching': 'Continue Watching',
          'Recommend Movies': 'Recommended Movies',
          'Short Films': 'Short Films',
          'Live Streaming': 'Live Streaming',
          'Most Watched Videos': 'Most Watched Videos',
          'Govt New Schemes': 'Govt New Schemes',
          'Live Stream': 'Live Stream',
          'Click on watch live': 'Click on watch live',
          'Watch Live': 'Watch Live',
          'Live stream will start soon...': 'Live stream will start soon...',
          'Live Stream': 'Live Stream',
          'Recommend Short Films': 'Recommended Short Films',
          'Most Watched Short Films': 'Most Watched Short Films',
          'Action Movies': 'Action Movies',
          'Crime Thriller': 'Crime Thriller',
          'Romantic': 'Romantic',
          'Music Album': 'Music Album',
          'Music videos': 'Music videos',
          'Trending Music': 'Trending Music',
          'Hot Music': 'Hot Music',
          "Please press back again to Exit": "Please press back again to Exit",
          "Video Resolution Quality": "Video Resolution Quality",
          'Already Downloded': 'Already Downloded',
          'Influencer': 'Influencer',
          'Please turn on your Mobile Data': 'Please turn on your Mobile Data',
          'Please turn on your Wifi': 'Please turn on your Wifi',
          'Already Downloaded': 'Already Downloaded',
          'Recommended Videos': 'Recommended Videos',
          'Upload Statement': 'Upload Statement',
          'No email': 'No email',
          'Available': 'Available',
          'Manage Profile': 'Manage Profile',
          'Notifications': 'Notifications',
          'Earnings': 'Earnings',
          'Start Watching': 'Start Watching',
          'Play Trailer': 'Play Trailer',
          "Enter Email or Mobile Number": "Enter Email or Mobile Number"
        }
      };
}
